/* ========================================================================== */
/* 1. NETTOYAGE COMPLET (DROP)                                                */
/* ========================================================================== */
/* On supprime d'abord la table de faits à cause des clés étrangères */
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE Fait_Evenement_Abonnement CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE Dim_Utilisateur CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE Dim_Abonnement CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE Dim_Geographie CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE Dim_Type_Evenement CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE Dim_Profil CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE Dim_Date CASCADE CONSTRAINTS PURGE';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP VIEW V_Dim_Date';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP VIEW V_Dim_Geographie';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP VIEW V_Dim_Utilisateur';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

/* ========================================================================== */
/* 2. CREATION DES DIMENSIONS                                                 */
/* ========================================================================== */

CREATE TABLE Dim_Date (
    Date_Key NUMBER PRIMARY KEY,
    Date_Complete DATE NOT NULL,
    Jour_Semaine VARCHAR2(15),
    Jour_Mois NUMBER,
    Mois_Nom VARCHAR2(15),
    Mois_Annee VARCHAR2(7),
    Trimestre VARCHAR2(2),
    Annee NUMBER,
    Est_Weekend CHAR(3),
    Est_Fin_De_Mois CHAR(3)
);

CREATE TABLE Dim_Geographie (
    Geo_Key NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    Pays VARCHAR2(50),
    Code_Pays_ISO CHAR(2),
    Region_Administrative VARCHAR2(50),
    Fuseau_Horaire VARCHAR2(50),
    Continent VARCHAR2(20),
    Est_Region_RGPD CHAR(3),
    Langue_Officielle_Pays VARCHAR2(20),
    Devise_Locale CHAR(3)
);

CREATE TABLE Dim_Utilisateur (
    Utilisateur_Key NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    ID_Utilisateur_Naturel VARCHAR2(50) NOT NULL,
    Date_Creation_Compte DATE,
    Langue_Navigateur_Inscription VARCHAR2(10),
    Device_Origine VARCHAR2(20),
    Statut_Actuel VARCHAR2(20),
    Derniere_Date_Activite DATE,
    Age_Compte_Jours NUMBER,
    Categorie_Utilisateur VARCHAR2(20)
);

CREATE TABLE Dim_Abonnement (
    Abonnement_Key NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    SKU_Abonnement VARCHAR2(50),
    Nom_Plan VARCHAR2(50),
    Type_Plan VARCHAR2(10),
    Frequence_Facturation VARCHAR2(20),
    Prix_Reference_EUR NUMBER(10, 2),
    Prix_Reference_USD NUMBER(10, 2),
    Devise_Reference CHAR(3),
    Date_Lancement_Plan DATE,
    Statut_Plan VARCHAR2(20)
);

CREATE TABLE Dim_Type_Evenement (
    Evenement_Key NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    Nom_Evenement VARCHAR2(50),
    Categorie_Evenement VARCHAR2(50),
    Declencheur_Evenement VARCHAR2(20),
    Description_Evenement VARCHAR2(255),
    Est_Evenement_Payant CHAR(3),
    Est_Evenement_Positif CHAR(3)
);

CREATE TABLE Dim_Profil (
    Profil_Key NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    Tranche_Age VARCHAR2(20),
    Categorie_socio_pro VARCHAR2(50)
);

/* ========================================================================== */
/* 3. CREATION DE LA TABLE DE FAITS                                           */
/* ========================================================================== */

CREATE TABLE Fait_Evenement_Abonnement (
    Date_Key NUMBER NOT NULL,
    Utilisateur_Key NUMBER NOT NULL,
    Abonnement_Key NUMBER NOT NULL,
    Geo_Key NUMBER NOT NULL,
    Evenement_Key NUMBER NOT NULL,
    Profil_Key NUMBER NOT NULL,
    Montant_Facture NUMBER(10, 2),
    Delta_MRR NUMBER(10, 2),
    CONSTRAINT FK_Fait_Date FOREIGN KEY (Date_Key) REFERENCES Dim_Date (Date_Key),
    CONSTRAINT FK_Fait_User FOREIGN KEY (Utilisateur_Key) REFERENCES Dim_Utilisateur (Utilisateur_Key),
    CONSTRAINT FK_Fait_Abo FOREIGN KEY (Abonnement_Key) REFERENCES Dim_Abonnement (Abonnement_Key),
    CONSTRAINT FK_Fait_Geo FOREIGN KEY (Geo_Key) REFERENCES Dim_Geographie (Geo_Key),
    CONSTRAINT FK_Fait_Event FOREIGN KEY (Evenement_Key) REFERENCES Dim_Type_Evenement (Evenement_Key),
    CONSTRAINT FK_Fait_Profil FOREIGN KEY (Profil_Key) REFERENCES Dim_Profil (Profil_Key)
);

/* ========================================================================== */
/* 4. VUES VIRTUELLES                                                         */
/* ========================================================================== */

CREATE OR REPLACE VIEW V_Dim_Date AS SELECT * FROM Dim_Date;
CREATE OR REPLACE VIEW V_Dim_Geographie AS SELECT * FROM Dim_Geographie;
CREATE OR REPLACE VIEW V_Dim_Utilisateur AS SELECT * FROM Dim_Utilisateur;